env:
  es6: true
  node: true
  browser: true
extends: plugin:prettier/recommended
ignorePatterns: node_modules
parser: "@typescript-eslint/parser"
parserOptions:
  requireConfigFile: false,
plugins:
  - prettier
rules:
  jsx-a11y/anchor-is-valid: off
  prettier/prettier: warn
