-- auto-generated definition
CREATE TABLE b_detail
(
    fac_uid  text NOT NULL
        CONSTRAINT b_detail_pk
            PRIMARY KEY,
    cat_funl selection DEFAULT '2'::selection,
    cat_funm selection DEFAULT '2'::selection,
    cat_funu selection DEFAULT '2'::selection,
    cat_impl selection DEFAULT '1'::selection,
    cat_impm selection DEFAULT '1'::selection,
    cat_impu selection DEFAULT '1'::selection,
    riv_widl numeric,
    riv_widm numeric,
    riv_widu numeric,
    bnk_hgtl numeric,
    bnk_hgtm numeric,
    bnk_hgtu numeric,
    crn_wdll numeric,
    crn_wdlm numeric,
    crn_wdlu numeric,
    crn_wdrl numeric,
    crn_wdrm numeric,
    crn_wdru numeric,
    dmg_lifl selection DEFAULT '0'::selection,
    dmg_lifm selection DEFAULT '0'::selection,
    dmg_lifu selection DEFAULT '0'::selection,
    dmg_prol selection DEFAULT '0'::selection,
    dmg_prom selection DEFAULT '0'::selection,
    dmg_prou selection DEFAULT '0'::selection,
    dmg_txtl text,
    dmg_txtm text,
    dmg_txtu text,
    fld_cdel selection DEFAULT '0'::selection,
    fld_cdem selection DEFAULT '0'::selection,
    fld_cdeu selection DEFAULT '0'::selection,
    fld_txtl text,
    fld_txtm text,
    fld_txtu text,
    bnk_stll selection DEFAULT '0'::selection,
    bnk_stlm selection DEFAULT '0'::selection,
    bnk_stlu selection DEFAULT '0'::selection,
    bnk_strl selection DEFAULT '0'::selection,
    bnk_strm selection DEFAULT '0'::selection,
    bnk_stru selection DEFAULT '0'::selection,
    rev_mall selection DEFAULT '2'::selection,
    rev_malm selection DEFAULT '2'::selection,
    rev_malu selection DEFAULT '2'::selection,
    rev_stll selection DEFAULT '1'::selection,
    rev_stlm selection DEFAULT '1'::selection,
    rev_stlu selection DEFAULT '1'::selection,
    rev_marl selection DEFAULT '2'::selection,
    rev_marm selection DEFAULT '2'::selection,
    rev_maru selection DEFAULT '2'::selection,
    rev_strl selection DEFAULT '1'::selection,
    rev_strm selection DEFAULT '1'::selection,
    rev_stru selection DEFAULT '1'::selection,
    dor_pasl selection DEFAULT '2'::selection,
    dor_pasm selection DEFAULT '2'::selection,
    dor_pasu selection DEFAULT '2'::selection,
    riv_chgl selection DEFAULT '0'::selection,
    riv_chgm selection DEFAULT '0'::selection,
    riv_chgu selection DEFAULT '0'::selection,
    riv_depl selection DEFAULT '1'::selection,
    riv_depm selection DEFAULT '1'::selection,
    riv_depu selection DEFAULT '1'::selection,
    riv_pltl selection DEFAULT '1'::selection,
    riv_pltm selection DEFAULT '1'::selection,
    riv_pltu selection DEFAULT '1'::selection,
    riv_posl selection DEFAULT '1'::selection,
    riv_posm selection DEFAULT '1'::selection,
    riv_posu selection DEFAULT '1'::selection,
    riv_dmgl selection DEFAULT '0'::selection,
    riv_dmgm selection DEFAULT '0'::selection,
    riv_dmgu selection DEFAULT '0'::selection,
    eva_prxl selection DEFAULT '0'::selection,
    eva_prxm selection DEFAULT '0'::selection,
    eva_prxu selection DEFAULT '0'::selection,
    eva_infl selection DEFAULT '0'::selection,
    eva_infm selection DEFAULT '0'::selection,
    eva_infu selection DEFAULT '0'::selection,
    eva_opel selection DEFAULT '0'::selection,
    eva_opem selection DEFAULT '0'::selection,
    eva_opeu selection DEFAULT '0'::selection,
    eva_opil text,
    eva_opim text,
    eva_opiu text
);

ALTER TABLE b_detail
    OWNER TO postgres;
